from tkinter import *
import tkinter as tk
import tkinter.messagebox
import tkinter.font as tkFont
from PIL import Image,ImageTk
import os
import sqlite3

def fest1(i,i1,i2,i3):
    connection = sqlite3.connect('NCD.db')
    cursor = connection.cursor()
    t=tk.Tk()
    t.title('CASE')
    w, h = t.winfo_screenwidth(), t.winfo_screenheight()
    t.geometry("%dx%d+0+0" % (w, h))

    def update_case():
        cursor.execute("Update CASE1 set CASENO=? where CASENO=?", (case_id1.get(), i[0][0],))
        cursor.execute("Update CASE1 set PENALCODETYPE=? where CASENO=?", (pno1.get(), i[0][0],))
        cursor.execute("Update CASE1 set SECTIONNUMBER =? where CASENO=?", (sn1.get(), i[0][0],))
        cursor.execute("Update CASE1 set POLICESTATION=? where CASENO=?", (ps1.get(), i[0][0],))
        cursor.execute("Update CASE1 set DESCRIPTION=? where CASENO=?", (desc1.get(), i[0][0],))
        cursor.execute("Update CASE1 set STATUS=? where CASENO=?", (status1.get(), i[0][0],))
        cursor.execute("Update CASE1 set OPENDATE=? where CASENO=?", (od1.get(), i[0][0],))
        cursor.execute("Update CASE1 set CLOSEDATE=? where CASENO=?", (cd1.get(), i[0][0],))
        cursor.execute("Update CASE2 set POLICEID=? where CASENO=?", (pi1.get(), i1[0][0],))
        cursor.execute("Update CASE3 set VFNAME=? where CASENO=?", (victim1.get(), i2[0][0],))
        cursor.execute("Update CASE3 set VMNAME=? where CASENO=?", (victim2.get(), i[0][0],))
        cursor.execute("Update CASE3 set VLNAME=? where CASENO=?", (victim3.get(), i[0][0],))
        cursor.execute("Update CASE3 set VAGE=? where CASENO=?", (age1.get(), i2[0][0],))
        cursor.execute("Update CASE3 set VADDRESS=? where CASENO=?", (address1.get(), i2[0][0],))
        cursor.execute("Update CASE4 set FIRNO=? where CASENO=?", (fr1.get(), i3[0][0],))
        connection.commit()

    ci = StringVar(t)
    frn = StringVar(t)
    pss = StringVar(t)
    des = StringVar(t)
    st = StringVar(t)
    o = StringVar(t)
    c = StringVar(t)
    vn = StringVar(t)
    vn1 = StringVar(t)
    vn2 = StringVar(t)
    ag = StringVar(t)
    pii = StringVar(t)
    pnoo = StringVar(t)
    snn = StringVar(t)

    def delete():
        cursor.execute('DELETE from CASE1 where CASENO=?', (i[0][0],))
        connection.commit()
        cursor.execute('DELETE from CASE2 where CASENO=?', (i1[0][0],))
        connection.commit()
        cursor.execute('DELETE from CASE2 where CASENO=?', (i2[0][0],))
        connection.commit()
        cursor.execute('DELETE from CASE4 where CASENO=?', (i3[0][0],))
        connection.commit()

        return
    victim=Label(t, text='Name of victim',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid")
    od=Label(t, text='OPENING DATE',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid")
    address=Label(t, text='ADDRESS',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid")
    victim1=Entry(t,font=tkFont.Font(family="Times New Roman", size=30),textvariable=vn, borderwidth=2, relief="solid")
    victim2 = Entry(t, font=tkFont.Font(family="Times New Roman", size=30), textvariable=vn1, borderwidth=2, relief="solid")
    victim3 = Entry(t, font=tkFont.Font(family="Times New Roman", size=30), textvariable=vn2, borderwidth=2,relief="solid")
    od1=Entry(t,font=tkFont.Font(family="Times New Roman", size=30),textvariable=o, borderwidth=2, relief="solid")
    address1=Entry(t,font=tkFont.Font(family="Times New Roman", size=30), textvariable=ci, relief="solid")
    #=Label(t, text='FIR', borderwidth=2, relief="solid")
    case_id=Label(t, text='CASE ID',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid")
    status=Label(t, text='status',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid")
    case_id1=Entry(t,font=tkFont.Font(family="Times New Roman", size=30),textvariable=ci, borderwidth=2, relief="solid")
    status1=Entry(t,font=tkFont.Font(family="Times New Roman", size=30),textvariable=st, borderwidth=2, relief="solid")
    #=Entry(t,font=tkFont.Font(family="Times New Roman", size=30), borderwidth=2, relief="solid")
    desc=Label(t, text='DESCRIPTION',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid")
    desc1=Entry(t,font=tkFont.Font(family="Times New Roman", size=30),textvariable=des, borderwidth=2, relief="solid")
    cd=Label(t, text='CLOSING DATE',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid")
    cd1=Entry(t,font=tkFont.Font(family="Times New Roman", size=30), textvariable=c,borderwidth=2, relief="solid")
    fr = Label(t, text='FIR NUMBER',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid")
    fr1 = Entry(t, font=tkFont.Font(family="Times New Roman", size=30), textvariable=frn, borderwidth=2, relief="solid")
    pi = Label(t, text='POLICE ID',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid")
    pi1 = Entry(t, font=tkFont.Font(family="Times New Roman", size=30), textvariable=pii, borderwidth=2, relief="solid")
    pno = Label(t, text='PENAL NUMBER',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid")
    pno1 = Entry(t, font=tkFont.Font(family="Times New Roman", size=30), textvariable=pnoo, borderwidth=2, relief="solid")
    sn = Label(t, text='SECTION NUMBER',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid")
    sn1 = Entry(t, font=tkFont.Font(family="Times New Roman", size=30), textvariable=snn, borderwidth=2,
                 relief="solid")
    #OptionList=[i3[0][1]]
    #v = tk.StringVar(t)
    #v.set('FIR NUMBER ')
    #fir= tk.OptionMenu(t, v, *OptionList)
    #OptionList2=[i1[0][1]]
    #OptionList3=[i[0][1]]
    #v2 = tk.StringVar(t)
    #v2.set('POLICE ID')
    #police_id= tk.OptionMenu(t, v2, *OptionList2)
    #v3 = tk.StringVar(t)
    #v3.set('PENAL NUMBER')
    #penal_no=tk.OptionMenu(t, v3, *OptionList3)
    ps=Label(t, text='POLICE STATION',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid")
    ps1=Entry(t,font=tkFont.Font(family="Times New Roman", size=30),textvariable=pss , borderwidth=2, relief="solid")
    age=Label(t, text='AGE',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid")
    age1=Entry(t,font=tkFont.Font(family="Times New Roman", size=30),textvariable=ag, borderwidth=2, relief="solid")
    delete=Button(t, text='delete',font=tkFont.Font(family="Times New Roman", size=16),command=delete, borderwidth=2, relief="solid")
    submit = Button(t, text='submit',font=tkFont.Font(family="Times New Roman", size=16), command=update_case, borderwidth=2, relief="solid")


    victim.place(x=50, y=150, width=150, height=70)
    age.place(x=500, y=50, width=150, height=70)
    address.place(x=850, y=50, width=150, height=70)
    victim1.place(x=250, y=150, width=150, height=70)
    victim2.place(x=450, y=150, width=150, height=70)
    victim3.place(x=650, y=150, width=150, height=70)
    age1.place(x=680, y=50, width=150, height=70)
    address1.place(x=1025, y=50, width=150, height=70)
    case_id.place(x=50, y=50, width=175, height=70)
    fr.place(x=50,y=450,width=150,height=70)
    fr1.place(x=250, y=450, width=150, height=70)
    case_id1.place(x=275, y=50, width=200, height=70)
    pi.place(x=50,y=550,width=100,height=70)
    pi1.place(x=250, y=550, width=100, height=70)
    status.place(x=900, y=250, width=100, height=70)
    status1.place(x=1025, y=250, width=100, height=70)
    pno.place(x=450, y=450, width=100, height=70)
    pno1.place(x=575, y=450, width=100, height=70)
    sn.place(x=400, y=550, width=150, height=70)
    sn1.place(x=600, y=550, width=150, height=70)
    #marks.place(x=50, y=350, width=300, height=70)
    #address.place(x=400, y=350, width=300, height=70)
    #penal_no.place(x=50, y=650, width=200, height=70)
    desc.place(x=550, y=350, width=100, height=70)
    desc1.place(x=675, y=350, width=100, height=70)
    ps.place(x=50, y=350, width=200, height=70)
    ps1.place(x=275, y=350, width=200, height=70)
    od.place(x=50, y=250, width=200, height=70)
    od1.place(x=275, y=250, width=200, height=70)
    cd.place(x=525,y=250,width=200,height=70)
    cd1.place(x=750,y=250,width=100,height=70)
    delete.place(x=1025, y=550, width=100, height=70)
    submit.place(x=1175, y=550, width=100, height=70)

    ci.set(i[0][0])
    #v3.set(i3[0][1])
    pss.set(i[0][3])
    des.set(i[0][4])
    st.set(i[0][5])
    o.set(i[0][6])
    c.set(i[0][7])
    vn.set(i2[0][1])
    vn1.set(i2[0][2])
    vn2.set(i2[0][3])
    ag.set(i2[0][4])
    #v.set(i[0][1])
    #v2.set(i[0][1])
    frn.set(i3[0][1])
    pnoo.set(i[0][1])
    pii.set(i1[0][1])
    snn.set(i[0][2])
    mainloop()